/*
 * https://tech.pjin.jp/blog/2017/04/18/unity_background_scroll/
 */

using UnityEngine;

/// <summary>
/// y”wŒi‚ÌƒRƒ“ƒgƒ[ƒ‹—pƒNƒ‰ƒXz
///     ”wŒi‚Í3–‡AƒJƒƒ‰‚©‚çŒ©Ø‚ê‚½‚ç‰ñ‚è‚Ş
/// </summary>
public class ControllBackground : MonoBehaviour
{

    // ”wŒi‚Ì–‡”
    int spriteCount = 3;
    // ”wŒi‚ª‰ñ‚è‚İ
    float rightOffset = 1.45f;
    float leftOffset = -0.4f;

    Transform bgTfm;
    SpriteRenderer mySpriteRndr;
    float width;

    void Start()
    {
        bgTfm = transform;
        mySpriteRndr = GetComponent<SpriteRenderer>();
        width = mySpriteRndr.bounds.size.x;
    }


    void Update()
    {
        // À•W•ÏŠ·
        Vector3 myViewport = Camera.main.WorldToViewportPoint(bgTfm.position);

        // ”wŒi‚Ì‰ñ‚è‚İ(ƒJƒƒ‰‚ªX²ƒvƒ‰ƒX•ûŒü‚ÉˆÚ“®)
        if (myViewport.x < leftOffset)
        {
            bgTfm.position += Vector3.right * (width * spriteCount);
        }
        // ”wŒi‚Ì‰ñ‚è‚İ(ƒJƒƒ‰‚ªX²ƒ}ƒCƒiƒX•ûŒü‚ÉˆÚ“®)
        else if (myViewport.x > rightOffset)
        {
            bgTfm.position -= Vector3.right * (width * spriteCount);
        }
    }
}
